export function parseNum(v) {
  if (v == null || String(v).trim() === '') return null;
  const s = String(v).replace(/[,$]/g, '').trim();
  const isPercent = s.endsWith('%');
  let n = parseFloat(s.replace('%', ''));
  if (isNaN(n)) return null;
  if (isPercent) n = n / 100;
  return n;
}

export function fmt(v, type) {
  if (v === null || v === undefined) return '';
  const n = Number(v);
  if (type === 'currency') return '$' + n.toLocaleString('en-AU', { minimumFractionDigits: 0, maximumFractionDigits: 0 });
  // KPI ratios are stored as decimals; standard percentage displays use two places.
  if (type === 'percent') return (n * 100).toFixed(2) + '%';
  if (type === 'percentWhole') return (n * 100).toFixed(0) + '%';
  return n.toLocaleString('en-AU', { maximumFractionDigits: 1 });
}

export const MONTH_NAMES = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

const PERIOD_PATTERN = /^(\d{4})-(\d{1,2})$/;

function periodMonthIndex(period) {
  const match = PERIOD_PATTERN.exec(String(period || ''));
  if (!match) return null;
  const year = Number(match[1]);
  const month = Number(match[2]);
  if (!Number.isInteger(year) || month < 1 || month > 12) return null;
  return year * 12 + month - 1;
}

export function filterPeriodsByTimeframe(periods, anchorPeriod, timeframe = '12M', customRange = null) {
  const validPeriods = (periods || []).filter(period => periodMonthIndex(period) !== null);
  if (validPeriods.length === 0) return [];

  const fallbackAnchor = validPeriods[validPeriods.length - 1];
  const resolvedAnchor = periodMonthIndex(anchorPeriod) === null ? fallbackAnchor : anchorPeriod;
  const anchorIndex = periodMonthIndex(resolvedAnchor);
  const [anchorYear, anchorMonth] = String(resolvedAnchor).split('-').map(Number);
  const monthWindow = { '3M': 3, '6M': 6, '12M': 12 }[timeframe];
  const financialYearStartIndex = (anchorMonth >= 7 ? anchorYear : anchorYear - 1) * 12 + 6;
  const customFromIndex = periodMonthIndex(customRange?.from);
  const customToIndex = periodMonthIndex(customRange?.to);
  const hasCustomRange = customFromIndex !== null && customToIndex !== null;
  const customStartIndex = hasCustomRange ? Math.min(customFromIndex, customToIndex) : null;
  const customEndIndex = hasCustomRange ? Math.min(Math.max(customFromIndex, customToIndex), anchorIndex) : null;

  return validPeriods.filter(period => {
    const periodIndex = periodMonthIndex(period);
    const distance = anchorIndex - periodIndex;
    if (distance < 0) return false;
    if (timeframe === 'YTD') return Number(period.split('-')[0]) === anchorYear;
    if (timeframe === 'FYTD') return periodIndex >= financialYearStartIndex;
    if (timeframe === 'CUSTOM') {
      if (!hasCustomRange) return distance < 12;
      return periodIndex >= customStartIndex && periodIndex <= customEndIndex;
    }
    if (monthWindow) return distance < monthWindow;
    return true;
  });
}

function ratioValue(row, field) {
  const value = parseNum(row?.[field]);
  if (!Number.isFinite(value)) return null;
  return Math.abs(value) > 2 ? value / 100 : value;
}

export const KPI_CONFIG = {
  'Total Sales': {
    format: 'currency',
    getValue: (row) => parseNum(row['Total Sales']),
    benchmarkType: 'min',
    description: 'Total revenue generated across all departments'
  },
  'Sales per RO': {
    format: 'currency',
    getValue: (row) => parseNum(row['Sales per RO']),
    benchmarkType: 'min',
    description: 'Average revenue generated per Repair Order'
  },
  'Panel Sales': {
    format: 'currency',
    getValue: (row) => parseNum(row['Panel Sales']),
    benchmarkType: 'min',
    description: 'Revenue generated by the panel department'
  },
  'Part Sales': {
    format: 'currency',
    getValue: (row) => parseNum(row['Part Sales']),
    benchmarkType: 'min',
    description: 'Revenue generated from replacement parts'
  },
  'Other Sales': {
    format: 'currency',
    getValue: (row) => parseNum(row['Other Sales']),
    benchmarkType: 'min',
    description: 'Revenue generated outside panel, paint and parts sales'
  },
  'Effective Labour Rate': {
    format: 'currency',
    getValue: (row) => parseNum(row['Effective Labour Rate']),
    benchmarkType: 'min',
    description: 'Average labour revenue earned for each sold labour hour'
  },
  'Effective Labour Cost': {
    format: 'currency',
    getValue: (row) => parseNum(row['Effective Labour Cost']),
    benchmarkType: 'max',
    description: 'Average labour cost incurred for each productive hour'
  },
  'Completed RO': {
    format: 'number',
    getValue: (row) => parseNum(row['Completed RO']),
    benchmarkType: 'min',
    description: 'Total number of Repair Orders completed in the period'
  },
  'Overall Efficiency': {
    format: 'percent',
    getValue: (row) => ratioValue(row, 'Overall Efficiency'),
    benchmarkType: 'min',
    description: 'Combined productive efficiency across panel and paint'
  },
  'Total Gross Profit %': {
    format: 'percent',
    getValue: (row) => ratioValue(row, 'Total Gross Profit %'),
    benchmarkType: 'min',
    description: 'Total gross profit margin as a percentage of sales'
  },
  'Total Gross Profit $': {
    format: 'currency',
    getValue: (row) => parseNum(row['Total Gross Profit $']),
    benchmarkType: 'min',
    description: 'Gross profit dollars retained after direct production costs'
  },
  'Panel Utilisation': {
    format: 'percent',
    getValue: (row) => ratioValue(row, 'Panel Utilisation'),
    benchmarkType: 'min',
    description: 'Available panel capacity converted into productive work'
  },
  'Paint Utilisation': {
    format: 'percent',
    getValue: (row) => ratioValue(row, 'Paint Utilisation'),
    benchmarkType: 'min',
    description: 'Available paint capacity converted into productive work'
  },
  'Panel Productive Efficiency': {
    format: 'percent',
    getValue: (row) => ratioValue(row, 'Panel Productive Efficiency'),
    benchmarkType: 'min',
    description: 'Panel hours produced compared with hours worked'
  },
  'Paint Productive Efficiency': {
    format: 'percent',
    getValue: (row) => ratioValue(row, 'Paint Productive Efficiency'),
    benchmarkType: 'min',
    description: 'Paint hours produced compared with hours worked'
  },
  'Cycle Time Total (K2K)': {
    format: 'number',
    getValue: (row) => parseNum(row['Cycle Time Total (K2K)']),
    benchmarkType: 'max',
    description: 'Average total key-to-key repair cycle time'
  },
  'Paint Hours per RO': {
    format: 'number',
    getValue: (row) => parseNum(row['Paint Hours per RO']),
    benchmarkType: 'min',
    description: 'Average paint labour hours sold per completed Repair Order'
  },
  'Paint Consumables': {
    format: 'currency',
    getValue: (row) => parseNum(row['Paint Consumables']),
    benchmarkType: 'max',
    description: 'Total paint consumable cost recorded for the period'
  },
  'Paint Sales': {
    format: 'currency',
    getValue: (row) => parseNum(row['Paint Sales']),
    benchmarkType: 'min',
    description: 'Total paint sales revenue'
  },
  'Paint Cost / Total Sales': {
    format: 'percent',
    getValue: (row) => {
      const paintCost = (parseNum(row['Paint Cost per RO']) || 0) * (parseNum(row['Completed RO']) || 0);
      const totalSales = parseNum(row['Total Sales']) || 0;
      return totalSales > 0 ? (paintCost / totalSales) : 0;
    },
    benchmarkType: 'max',
    description: 'Ratio of paint costs to total business revenue'
  },
  'Paint Cost / RO': {
    format: 'currency',
    getValue: (row) => parseNum(row['Paint Cost per RO']),
    benchmarkType: 'max',
    description: 'Average cost of paint materials per Repair Order'
  },
  'Booth Cycle Time': {
    format: 'number',
    getValue: (row) => parseNum(row['Booth Cycle Time']),
    benchmarkType: 'max',
    description: 'Average hours a vehicle spends in the spray booth'
  },
  'Liquid Cost to Refinish': {
    format: 'percent',
    getValue: (row) => {
      const paintCost = (parseNum(row['Paint Cost per RO']) || 0) * (parseNum(row['Completed RO']) || 0);
      const paintSales = parseNum(row['Paint Sales']) || 0;
      return paintSales > 0 ? (paintCost / paintSales) : 0;
    },
    benchmarkType: 'max',
    description: 'Cost of paint liquids relative to refinish labour sales'
  },
  'VPD / Per Booth': {
    format: 'number',
    getValue: (row) => parseNum(row['Vehicles per Day per Booth']),
    benchmarkType: 'min',
    description: 'Average number of vehicles processed through each booth daily'
  },
  'Return on Paint Labour': {
    format: 'percent',
    getValue: (row) => {
      const pSales = parseNum(row['Paint Sales']);
      const pCost = parseNum(row['Paint Labour Costs']);
      return pCost > 0 ? (pSales / pCost) : 0;
    },
    benchmarkType: 'min',
    description: 'Return on investment for paint labour'
  },
  'Paint Revenue P/V': {
    format: 'currency',
    getValue: (row) => {
      const pSales = parseNum(row['Paint Sales']);
      const cRO = parseNum(row['Completed RO']);
      return cRO > 0 ? (pSales / cRO) : 0;
    },
    benchmarkType: 'min',
    description: 'Paint revenue per completed vehicle'
  }
};
